if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
if(!require(caret)) install.packages("caret", repos = "http://cran.us.r-project.org")
if(!require(data.table)) install.packages("data.table", repos = "http://cran.us.r-project.org")
if(!require(recosystem)) install.packages("recosystem", repos = "http://cran.us.r-project.org")
if(!require(anytime)) install.packages("anytime", repos = "http://cran.us.r-project.org")
if(!require(gridExtra)) install.packages("gridExtra", repos = "http://cran.us.r-project.org")
if(!require(broom)) install.packages("broom", repos = "http://cran.us.r-project.org")
if(!require(rpart.plot)) install.packages("rpart.plot", repos = "http://cran.us.r-project.org")



library(tidyverse)
library(caret)
library(data.table)
library(tinytex)
library(dbplyr)
library(dplyr)
library(caret)
library(dslabs)
library(ggplot2)
library(knitr)
library(latexpdf)
library(rmarkdown)
library(recosystem)
library(tidyverse)
library(tidyr)
library(gridExtra)
library(broom)
library(rpart)
library(rpart.plot)
library(httr)


## The download from kaggle proved problematic as I could only download the file as text when using the download.file or 
## read.csv functions. Therefore I had to use an indirect method to download the data into R.

## We download the dataset from 
# https://www.kaggle.com/stefanoleone992/fifa-20-complete-player-dataset/download and save in our working directory,
# then read in the csv file named players_20.csv


data_import <- read.csv("https://raw.githubusercontent.com/dan-reeves/Fifa_players/master/players_20.csv")
head(data_import)

## There are many variables in this dataset that are generated by the game which are purely subjective, and I therefore
## discard them from my analysis. These include a players overall rating and skill attributes.
## We choose the features of relevance
players_data <- data_import %>% select(sofifa_id, short_name, value_eur, age, height_cm, weight_kg, nationality, club,
                                       player_positions, international_reputation, team_position, contract_valid_until)

## Removing players who are not contracted to a club, otherwise known as free agents.
contracted_players <- players_data %>% filter(!is.na(contract_valid_until))

## Now we alter the contract column to tell us how many years are left on the contract rather than the year it expires.
altered_contract_players <- contracted_players %>% mutate(yrs_left_on_contract = contract_valid_until-2019)


## Now we introduce a column which determines the class of the player, meaning whether they are an attacker or defender etc
# Position Class
attacker = c("ST", "LW", "RW", "LF", "RF", "CF")
midfielder = c("CM", "CDM", "CAM", "RM", "LM")
position_classes <- altered_contract_players %>% mutate(strongest_position = str_extract(player_positions, "^[A-Z]{2,3}")) %>% 
  mutate(position_class = as.factor(
    if_else(strongest_position %in% attacker, "Attacker",
          if_else(strongest_position %in% midfielder, "Midfielder", 
                  if_else(strongest_position == "GK", "Goal_Keeper", "Defender")))))

## Our ext task is classify the players importance to the team/club. 
first_team_players <- position_classes %>% mutate(squad_rank = as.factor(
  if_else(team_position == "SUB", "Bench",
          if_else(team_position == "RES", "Reserves", "First_Team"))))

## Now we add a feature to classify the league in player plays in. Our focus is on the top european leagues and english leagues.
## These leagues are: Premier League, La Liga, Bundesliga, Serie A, Ligue 1 and the Championship.
## The first issue however is that many foreign teams have characters which are not supported, making this step a little more
## complicated than it might have been. 

## First we must make adjustments for these characters.

correct_clubs <- first_team_players %>% mutate(Club = as.factor(
  ifelse(club == "AS Saint-Ã‰tienne", "AS Saint-Étienne", 
         ifelse(club == "NÃ®mes Olympique", "Nîmes Olympique", 
                ifelse(club == "FC Bayern MÃ¼nchen", "FC Bayern München",
                       ifelse(club == "Borussia MÃ¶nchengladbach", "Borussia Mönchengladbach",
                              ifelse(club == "Fortuna DÃ¼sseldorf", "Fortuna Düsseldorf",
                                     ifelse(club == "1. FC KÃ¶ln", "1. FC Köln", 
                                            ifelse(club == "AtlÃ©tico Madrid", "Atlético Madrid",
                                                   ifelse(club == "CD LeganÃ©s", "CD Leganés",
                                                          ifelse(club == "Deportivo AlavÃ©s", "Deportivo Alavés",
                                                                 ifelse(club == "MalmÃ¶ FF", "Malmö FF",
                                                                        ifelse(club=="FC KÃ¸benhavn", "FC København",
                                                                               ifelse(club=="Standard de LiÃ¨ge", "Standard Liège",
                                                                                      ifelse(club=="VitÃ³ria GuimarÃ£es", "Vitória de Guimarães",
                                                                                             ifelse(club=="Medipol BaÅŸakÅŸehir FK", "Medipol Başakşehir FK",
                                                                                                    ifelse(club=="BeÅŸiktaÅŸ JK", "Beşiktaş JK", club)))))))))))))))))




premier_league <- c(
  "Arsenal", "Aston Villa", "Bournemouth", "Brighton & Hove Albion", "Burnley",
  "Chelsea", "Crystal Palace", "Everton", "Leicester City", "Liverpool", "Manchester City",
  "Manchester United", "Newcastle United", "Norwich City", "Sheffield United", "Southampton", 
  "Tottenham Hotspur", "Watford", "West Ham United", "Wolverhampton Wanderers")

la_liga <- c(
  "Athletic Club de Bilbao", "Atlético Madrid", "CA Osasuna", "CD Leganés",
  "Deportivo Alavés", "FC Barcelona", "Getafe CF", "Granada CF", 
  "Levante UD", "RC Celta", "RCD Espanyol", "RCD Mallorca",
  "Real Betis", "Real Madrid", "Real Sociedad", "Real Valladolid CF",
  "SD Eibar", "Sevilla FC", "Valencia CF", "Villarreal CF")

bundesliga <- c(
  "1. FC Köln", "1. FC Union Berlin", "1. FSV Mainz 05", "Bayer 04 Leverkusen", 
  "FC Bayern München", "Borussia Dortmund", "Borussia Mönchengladbach", "Eintracht Frankfurt",
  "FC Augsburg", "FC Schalke 04", "Fortuna Düsseldorf", "Hertha BSC", "RB Leipzig", 
  "SC Freiburg", "SC Paderborn 07", "TSG 1899 Hoffenheim", "VfL Wolfsburg", "SV Werder Bremen")

serie_a <- c(
  "Atalanta", "Bologna", "Brescia", "Cagliari", "Fiorentina", "Genoa", "Hellas Verona",
  "Inter", "Juventus", "Lazio", "Lecce", "Milan", "Napoli", "Parma", "Roma", "Sampdoria", 
  "Sassuolo", "SPAL", "Torino", "Udinese")

ligue1 <- c(
  "Amiens SC", "Angers SCO", "AS Monaco", "AS Saint-Étienne", "Dijon FCO", "FC Girondins de Bordeaux", 
  "FC Metz", "FC Nantes",  "LOSC Lille", "Montpellier HSC", "Nîmes Olympique", 
  "OGC Nice", "Olympique Lyonnais","Olympique de Marseille", "Paris Saint-Germain", 
  "RC Strasbourg Alsace", "Stade Brestois 29", "Stade de Reims", "Stade Rennais FC", "Toulouse Football Club")

championship <- c(
  "Barnsley", "Birmingham City", "Blackburn Rovers", "Brentford", "Bristol City", "Cardiff City", 
  "Charlton Athletic", "Derby County", "Fulham", "Huddersfield Town", "Hull City", "Leeds United",
  "Luton Town", "Middlesbrough", "Millwall", "Nottingham Forest", "Preston North End", "Queens Park Rangers",
  "Reading", "Stoke City", "Swansea City", "Sheffield Wednesday", "West Bromwich Albion", "Wigan Athletic")

Champions_League <- c(
  "Paris Saint-Germain", "Real Madrid", "FC Bayern München", "Tottenham Hotspur", "Manchester City", "Atalanta", 
  "Juventus", "Atlético Madrid", "Bayer 04 Leverkusen", "Liverpool", "Napoli", "FC Barcelona", "Borussia Dortmund", 
  "Inter", "RB Leipzig", "Olympique Lyonnais", "Valencia CF", "Chelsea", "Club Brugge KV", "Galatasaray SK",
  "Olympiacos CFP", "Shakhtar Donetsk", "Dinamo Zagreb", "Lokomotiv Moscow", "FC Red Bull Salzburg", "KRC Genk",
  "SK Slavia Praha", "SL Benfica", "LOSC Lille", "Ajax")  
##### Red Star Belgrade and Zenit are not in the dataset ######################

Europa_League <- c(
  "Sevilla FC", "Getafe CF", "Lazio", "Stade Rennais FC", "Arsenal", "Eintracht Frankfurt", "RCD Espanyol",
  "VfL Wolfsburg", "AS Saint-Étienne", "Roma", "Borussia Mönchengladbach", "Wolverhampton Wanderers", "Manchester United",
  "Malmö FF", "FC København", "Dynamo Kyiv", "FC Lugano", "FC Basel 1893", "LASK Linz", "Sporting CP", "PSV",
  "Rosenborg BK", "Celtic", "CFR Cluj", "Standard Liège", "Vitória de Guimarães", "FC Porto", "Rangers FC",
  "BSC Young Boys", "Feyenoord", "PFC CSKA Moscow", "KAA Gent", "Medipol Başakşehir FK", "Wolfsberger AC", 
  "SC Braga", "Beşiktaş JK", "AZ Alkmaar") 
###### APOEL, Qarabag FK, F91 Dudelange, Krasnodar, Trabzonspor FC, PFC Ludogorets Razgrad, Ferencvárosi TC, FC Oleksandriya,
# ŠK Slovan Bratislava, FK Partizan and FC Astana are not in the database. ###############################


## Now we assign the league each player plays in and add a feature determining if the player plays in elite european competition.
added_leagues <- correct_clubs %>% mutate(league = as.factor(
  ifelse(Club %in% premier_league, "Premier League",
         ifelse(Club %in% la_liga, "La Liga", 
                ifelse(Club %in% bundesliga, "Bundesliga",
                       ifelse(Club %in% serie_a, "Serie A",
                              ifelse(Club %in% ligue1, "Ligue 1",
                                     ifelse(Club %in% championship, "Championship", "other"))))))),
  european_competition = as.factor(
    ifelse(Club %in% Champions_League, "Champions League", 
           ifelse(Club %in% Europa_League, "Europa League", "none"))))

## My next task is to sort an official player ID system.
add_player_id <- added_leagues %>% arrange(sofifa_id) %>% mutate(Player_ID = row_number())

## Finally we select the features we want to continue with
dataset <- add_player_id %>% select(Player_ID, short_name, value_eur, age, Club, league, nationality, strongest_position,
                                    position_class, squad_rank, european_competition, international_reputation, 
                                    yrs_left_on_contract)
dataset$nationality <- as.factor(dataset$nationality)
dataset$strongest_position <- as.factor(dataset$strongest_position)
head(dataset)



################################################################################################################################
################################################################################################################################


# Now we create the train and test set partition. The test set wil be one tenth of the full dataset.
set.seed(123, sample.kind="Rounding")

test_index <- createDataPartition(y = dataset$Player_ID, times = 1, p = 0.1, list = FALSE)
training_data <- dataset[-test_index,]
validation_set <- dataset[test_index,] ## The validation set shall be saved for final testing to avoid overtraining.

######    NOW WE CAN BEGIN THE DATA VISUALISATION ###############################################################
# We now look to explore the data to find relationships between the features. Our aim is to explain as much of the behaviour
# of the players valuations as possible.

## Below we see the average value of footballers against their age.
training_data %>% group_by(age) %>% summarise(n = n(), avg_age_value = mean(value_eur)) %>% mutate(total = n) %>%
  ggplot(aes(age, avg_age_value)) +
  geom_point() +
  geom_smooth()
## We can see a clear trend which we would expect in this situation. A players value peaks around the late 20's, when we expect
## a player to be in their prime.

plot_gk <- training_data %>% filter(strongest_position == "GK") %>% group_by(age) %>% 
  summarise(n = n(), avg_age_value_goalkeepers = mean(value_eur)) %>% mutate(total = n) %>%
  ggplot(aes(age, avg_age_value_goalkeepers)) + 
  labs(x = "Age of Goal Keeper", y = "Average value per age") +
  geom_point() +
  geom_smooth()
plot_of <- training_data %>% filter(strongest_position != "GK") %>% group_by(age) %>% 
  summarise(n = n(), avg_age_value_outfielders = mean(value_eur)) %>% mutate(total = n) %>%
  ggplot(aes(age, avg_age_value_outfielders)) +
  labs(x = "Age of Out fielder", y = "Average value per age") +
  geom_point() +
  geom_smooth()
grid.arrange(plot_gk, plot_of)
## We can see in the comparison between keepers and outfielders, that gks have an extended shelf life so to speak. Goal keepers
## often play at the highest level long into their 40's. This is evidence of how both age and position can have an effect on 
## the value of a player.

## Below we see the relationship between the values of players and the leagues they play in.
ggplot(training_data, aes(x = factor(league, level = c("Premier League", "La Liga", "Bundesliga", "Serie A", 
                                                       "Ligue 1", "Championship", "other")), y = value_eur)) + 
  geom_boxplot(outlier.color = "red", outlier.size = 1) + 
  stat_summary(fun = mean, geom = "point", shape = 3) +
  labs(x = "League", y = "Player Value (Euro)")
## We can see that the league a player plays in, especially if it's one of europes elite leagues, has an effect on the value of the
## player. We would of course expect to see the best players play in the most reputable leagues.



## We can investigate positions against value
training_data %>% group_by(position_class) %>% 
  summarise(avg_value_per_class = mean(value_eur)) %>%
  ggplot(aes(x = factor(position_class, level = c("Attacker", "Midfielder", "Defender", "Goal_Keeper")), y = avg_value_per_class)) +
  labs(x = "Position Class", y = "Average Value per position class") +
  geom_bar(stat = "identity")
## We see more evidence of the effect that the position has on the valuation of a player. The market values attacking players 
## higher. This makes some intuitive sense, the attacking players are more attractive to fans and create more income opportunities
## by way of shirt sales and gate receipts.



# We look closer at the individual positions.
training_data %>% group_by(strongest_position) %>%
  summarise(avg_value_per_position = mean(value_eur)) %>%
  ggplot(aes(x = factor(strongest_position, level = c("CF", "LW", "RW", "ST", "CAM", "CM", "LM", "RM","CDM", "LWB", "RWB",
                                                      "LB", "RB", "CB", "GK")), y = avg_value_per_position)) +
  labs(x = "Player Position", y = "Average Value per Position") +
  geom_bar(stat = "identity")
## Here we see a more detailed breakdown of average value against each indiviual position. We can see closely how the attacking 
## positions are valued higher against the defensive roles.



## We can take a look at how the role of a player within a club can impact on the players value.
training_data %>% group_by(squad_rank) %>%
  summarise(avg_value_per_rank = mean(value_eur)) %>%
  ggplot(aes(x = factor(squad_rank, level = c("First_Team", "Bench", "Reserves")), y = avg_value_per_rank)) +
  labs(x = "Squad Role", y = "Average Value per Rank") +
  geom_bar(stat = "identity")
## As we can see the trend suggests that the greater the responsibility of the player, the higher the players value. This makes
## sense as you would expect the better players to be in the starting eleven more often than not. We also expect the players
## which are playing more often to be showcasing their worth more and be of a higher level of match fitness.



## We can investigate the impact that continental competition has on the value of a player.
training_data %>% group_by(european_competition) %>%
  summarise(avg_value_per_comp = mean(value_eur)) %>% 
  ggplot(aes(x = factor(european_competition, level = c("Champions League", "Europa League", "none")), y = avg_value_per_comp)) +
  labs(x = "Competition", y = "Average Value per Competition") +
  geom_bar(stat = "identity")
## We see strong evidence that there exists a continental competition effect. We see players who play in the Champions league are
## valued significantly higher on average than those even in the europa league.


# We investigate the effect the international reputation of the player has on the players value.
training_data %>% group_by(international_reputation) %>%
  summarise(avg_value_per_int_rep = mean(value_eur)) %>% 
  ggplot(aes(x = factor(international_reputation, level = c("5", "4", "3", "2", "1")), y = avg_value_per_int_rep)) +
  labs(x = "International Reputation", y = "Average Value per Reputation rank (based on a 5 star system)") +
  geom_bar(stat = "identity")
## We can see the value of a player is greatly influenced by the international reputation of a player. This is what we expected, 
## as a player who performs to the highest level on the international stage will be a more attractive asset to clubs.

# We can see how the remaining contract length can effect the value of a player.
training_data %>% group_by(yrs_left_on_contract) %>%
  summarise(avg_value_per_deal_len = mean(value_eur)) %>%
  ggplot(aes(x = factor(yrs_left_on_contract, level = c("7", "6", "5", "4", "3", "2", "1", "0")), y = avg_value_per_deal_len)) +
  labs(x = "Years left on current deal", y = "Average Value per deal length") +
  geom_bar(stat = "identity")
## We can clearly see the effect of the contract length, as we would expect, the longer left on the deal the greater the value 
## of the player as more money is required to buy them out of the contract.



###############################################################################################################################
##################################################### BUILDING THE MODEL ######################################################

# We again split the dataset into a train and test set
set.seed(123, sample.kind="Rounding")

test_index_2 <- createDataPartition(y = training_data$Player_ID, times = 1, p = 0.1, list = FALSE)
train <- training_data[-test_index_2,]
test <- training_data[test_index_2,]

## We define our RMSE function as
RMSE <- function(true_value, predicted_value){
  sqrt(mean((true_value - predicted_value)^2))
}

## We set mu_hat to be the average value in Euros of all players:
mu_hat <- mean(train$value_eur)
naive_rmse <- RMSE(test$value_eur, mu_hat)
rmse_results <- data.frame(method = "Just the average", RMSE = naive_rmse)
## As we build upon this model we shall add each result to this table to track our progression.

# We now define residuals for each effect in order to add to the model
age_effect <- train %>% group_by(age) %>%
  summarise(b_age = mean(value_eur - mu_hat))

league_effect <- train %>% 
  left_join(age_effect, by = "age") %>%
  group_by(league) %>% 
  summarise(b_league = mean(value_eur - mu_hat - b_age))

position_effect <- train %>% 
  left_join(age_effect, by = "age") %>%
  left_join(league_effect, by = "league") %>%
  group_by(strongest_position) %>%
  summarise(b_pos = mean(value_eur - mu_hat - b_age - b_league))

role_effect <- train %>%
  left_join(age_effect, by = "age") %>%
  left_join(league_effect, by = "league") %>%
  left_join(position_effect, by = "strongest_position") %>%
  group_by(squad_rank) %>%
  summarise(b_role = mean(value_eur - mu_hat - b_age - b_league - b_pos))

euro_effect <- train %>% 
  left_join(age_effect, by = "age") %>%
  left_join(league_effect, by = "league") %>%
  left_join(position_effect, by = "strongest_position") %>%
  left_join(role_effect, by = "squad_rank") %>%
  group_by(european_competition) %>%
  summarise(b_euro = mean(value_eur - mu_hat - b_age - b_league - b_pos - b_role))

international_effect <- train %>%
  left_join(age_effect, by = "age") %>%
  left_join(league_effect, by = "league") %>%
  left_join(position_effect, by = "strongest_position") %>%
  left_join(role_effect, by = "squad_rank") %>%
  left_join(euro_effect, by = "european_competition") %>%
  group_by(international_reputation) %>%
  summarise(b_int_rep = mean(value_eur - mu_hat - b_age - b_league - b_pos - b_role - b_euro))

contract_effect <- train %>%
  left_join(age_effect, by = "age") %>%
  left_join(league_effect, by = "league") %>%
  left_join(position_effect, by = "strongest_position") %>%
  left_join(role_effect, by = "squad_rank") %>%
  left_join(euro_effect, by = "european_competition") %>%
  left_join(international_effect, by = "international_reputation") %>%
  group_by(yrs_left_on_contract) %>%
  summarise(b_contract = mean(value_eur - mu_hat - b_age - b_league - b_pos - b_role - b_euro - b_int_rep))


pred_values <- test %>%
  left_join(age_effect, by = "age") %>%
  left_join(league_effect, by = "league") %>%
  left_join(position_effect, by = "strongest_position") %>%
  left_join(role_effect, by = "squad_rank") %>%
  left_join(euro_effect, by = "european_competition") %>%
  left_join(international_effect, by = "international_reputation") %>%
  left_join(contract_effect, by = "yrs_left_on_contract") %>%
  mutate(pred = mu_hat + b_age + b_league + b_pos + b_role + b_euro + b_int_rep + b_contract) %>% 
  .$pred
pred_values <- data.frame(pred_values) %>% mutate(adj = case_when(pred_values<= 0 ~ 0, pred_values > 0 ~ pred_values)) %>%
  .$adj
## adjusting to ensure no negative value predictions. Enforcing a minimum value of 0.
## We now have a model that builds upon the average mu_hat by adding residual effects of each feature. 
qplot(test$value_eur, pred_values)

effects_model <- RMSE(test$value_eur, pred_values)
rmse_results <- bind_rows(rmse_results, data_frame(method="Effects Model", RMSE = effects_model))
## We add this model to our table and see an immediate improvement on our naive average model.



###############################################################################################################################
######################################### REGULARIZATION ######################################################################


# We shall define a function to find a value of alpha to use as our tuning parameter

alphas <- seq(0, 1000, 2) # Here we define a vector of possible alpha values to be passed through the function.
RMSE_result <- sapply(alphas, function(A){
  mu = mean(train$value_eur)
  age_effect <- train %>% group_by(age) %>% summarise(b_age = sum(value_eur - mu)/(n() + A))
  league_effect <- train %>% 
    left_join(age_effect, by = "age") %>%
    group_by(league) %>% summarise(b_league = sum(value_eur - mu - b_age)/(n() + A))
  position_effect <- train %>% 
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    group_by(strongest_position) %>% summarise(b_pos = sum(value_eur - mu - b_age - b_league)/(n() + A))
  role_effect <- train %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    group_by(squad_rank) %>% summarise(b_role = sum(value_eur - mu - b_age - b_league - b_pos)/(n() + A))
  euro_effect <- train %>% 
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    group_by(european_competition) %>% summarise(b_euro = sum(value_eur - mu - b_age - b_league - b_pos - b_role)/(n() + A))
  international_effect <- train %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    left_join(euro_effect, by = "european_competition") %>%
    group_by(international_reputation) %>% 
    summarise(b_int_rep = sum(value_eur - mu - b_age - b_league - b_pos - b_role - b_euro)/(n() + A))
  contract_effect <- train %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    left_join(euro_effect, by = "european_competition") %>%
    left_join(international_effect, by = "international_reputation") %>% group_by(yrs_left_on_contract) %>%
    summarise(b_contract = sum(value_eur - mu - b_age - b_league - b_pos - b_role - b_euro - b_int_rep)/(n() + A))
  pred_values <- test %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    left_join(euro_effect, by = "european_competition") %>%
    left_join(international_effect, by = "international_reputation") %>%
    left_join(contract_effect, by = "yrs_left_on_contract") %>%
    mutate(pred = mu_hat + b_age + b_league + b_pos + b_role + b_euro + b_int_rep + b_contract) %>% 
    .$pred
  pred_values <- data.frame(pred_values) %>% mutate(adj = case_when(pred_values<= 0 ~ 0, pred_values > 0 ~ pred_values)) %>%
    .$adj
  return(RMSE(test$value_eur, pred_values)) ## Each alpha is passed through and the resulting RMSE is stored in each scenario.
})
## Now we can extract the optimal RMSE and the corresponding optimal value for alpha.
qplot(alphas, RMSE_result)
opt_alpha <- alphas[which.min(RMSE_result)]
## Gives optimal alpha = 14, so now we look for the value of Alpha in a more concentrated range.

alphas_conc <- seq(13, 15, 0.005) # Here we define a vector of possible alpha values to be passed through the function.
RMSE_result_conc <- sapply(alphas_conc, function(A){
  mu = mean(train$value_eur)
  age_effect <- train %>% group_by(age) %>% summarise(b_age = sum(value_eur - mu)/(n() + A))
  league_effect <- train %>% 
    left_join(age_effect, by = "age") %>%
    group_by(league) %>% summarise(b_league = sum(value_eur - mu - b_age)/(n() + A))
  position_effect <- train %>% 
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    group_by(strongest_position) %>% summarise(b_pos = sum(value_eur - mu - b_age - b_league)/(n() + A))
  role_effect <- train %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    group_by(squad_rank) %>% summarise(b_role = sum(value_eur - mu - b_age - b_league - b_pos)/(n() + A))
  euro_effect <- train %>% 
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    group_by(european_competition) %>% summarise(b_euro = sum(value_eur - mu - b_age - b_league - b_pos - b_role)/(n() + A))
  international_effect <- train %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    left_join(euro_effect, by = "european_competition") %>%
    group_by(international_reputation) %>% 
    summarise(b_int_rep = sum(value_eur - mu - b_age - b_league - b_pos - b_role - b_euro)/(n() + A))
  contract_effect <- train %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    left_join(euro_effect, by = "european_competition") %>%
    left_join(international_effect, by = "international_reputation") %>% group_by(yrs_left_on_contract) %>%
    summarise(b_contract = sum(value_eur - mu - b_age - b_league - b_pos - b_role - b_euro - b_int_rep)/(n() + A))
  pred_values <- test %>%
    left_join(age_effect, by = "age") %>%
    left_join(league_effect, by = "league") %>%
    left_join(position_effect, by = "strongest_position") %>%
    left_join(role_effect, by = "squad_rank") %>%
    left_join(euro_effect, by = "european_competition") %>%
    left_join(international_effect, by = "international_reputation") %>%
    left_join(contract_effect, by = "yrs_left_on_contract") %>%
    mutate(pred = mu_hat + b_age + b_league + b_pos + b_role + b_euro + b_int_rep + b_contract) %>% 
    .$pred
  pred_values <- data.frame(pred_values) %>% mutate(adj = case_when(pred_values<= 0 ~ 0, pred_values > 0 ~ pred_values)) %>%
    .$adj
  return(RMSE(test$value_eur, pred_values)) ## Each alpha is passed through and the resulting RMSE is stored in each scenario.
})
 
qplot(alphas_conc, RMSE_result_conc)
opt_alpha_conc <- alphas_conc[which.min(RMSE_result_conc)]
effect_with_reg <- RMSE_result_conc[which.min(RMSE_result_conc)]

## So we have now that the optimal value of alpha is 13.82 and the related RMSE is 3700723. A small improvement.
rmse_results <- bind_rows(rmse_results, data_frame(method="Effects Modelwith Regularization", RMSE = effect_with_reg))
 



###############################################################################################################################
####################################### REGRESSION MODELS ######################################################################

## Due to the size of the dataset we shall use a much smaller section of the data to correct the code for the model, then use 
## the full training data to train the model.

## We want to use train and test as our datasets to build the model but we shall first use a small subset of the train set
## to ensure the code works.
set.seed(123, sample.kind="Rounding")
lm_model_index <- createDataPartition(y = train$Player_ID, times = 1, p = 0.05, list = FALSE)
lm_train_small <- train[lm_model_index,]
## We begin with a linear regression model
fit_small <- lm_train_small %>% lm(value_eur ~ age + league + strongest_position + squad_rank + 
                               european_competition + international_reputation + yrs_left_on_contract, data = .)
coefs <- tidy(fit_small)

experi <- as.data.frame(coefs)
experi$p.value
experi$term[which(experi$p.value>0.1)]

set.seed(123, sample.kind="Rounding")
lm_model_index_2 <- createDataPartition(y = test$Player_ID, times = 1, p = 0.05, list = FALSE)
lm_test_small <- test[lm_model_index_2,]

fake_predict <- lm_test_small %>% predict(fit_small, newdata =.)

lm_test_small %>% mutate(predictions = predict(fit_small, newdata = .)) %>%
  mutate(adjusted_predict = case_when(predictions <= 0 ~ 0, predictions > 0 ~ predictions)) %>%
ggplot(aes(value_eur, adjusted_predict)) +
  labs(x = "True Value", y = "Predicted Value") +
  geom_point()+ geom_abline()



## Now that we have working code we can look to build as accurate a model as possible.


fit <- train %>% lm(value_eur ~ age + league + strongest_position + squad_rank + 
                      european_competition + international_reputation + yrs_left_on_contract, data = .)

lm_coefs <- as.data.frame(tidy(fit))
lm_coefs$term[which(lm_coefs$p.value>0.01)]  ## This helps us to see the features which do not help. If the p value is very low
## we can reject the null hypothesis that the coefficient is equal to zero.
lm_coefs$p.value[which(lm_coefs$p.value>0.01)]


model_predictions <- test %>% predict(fit, newdata = .) 
adj_model_predict <- case_when(model_predictions <= 0 ~ 0, model_predictions > 0 ~ model_predictions)
linear_regression_model <- RMSE(test$value_eur, adj_model_predict)
rmse_results <- bind_rows(rmse_results, data_frame(method="Linear Regression Model", RMSE = linear_regression_model))


test %>% mutate(predictions = predict(fit, newdata = .)) %>%
  mutate(adjusted_predict = case_when(predictions <= 0 ~ 0, predictions > 0 ~ predictions)) %>%
  ggplot(aes(value_eur, adjusted_predict)) +
  labs(x = "True Value", y = "Predicted Value") +
  geom_point()+ geom_abline()
## We can see the model performs well for lesser valued players but undervalues the more premium players.



## Next we shall use a regression tree ####################################################################################


## We again need to use a smaller version of the data set to obtain the correct code so that the computation time is minimized.
set.seed(123, sample.kind="Rounding")
RT_model_index <- createDataPartition(y = train$Player_ID, times = 1, p = 0.1, list = FALSE)
RT_train_small <- train[RT_model_index,]

set.seed(123, sample.kind="Rounding")
RT_model_index_2 <- createDataPartition(y = test$Player_ID, times = 1, p = 0.1, list = FALSE)
RT_test_small <- test[RT_model_index_2,]


RT_small_fit_tune <- train(value_eur ~ age + league + strongest_position + squad_rank + 
                        european_competition + international_reputation + yrs_left_on_contract,
                      method = "rpart", tuneGrid = data.frame(cp = seq(0, 0.01, len = 100)), data = RT_train_small)
RT_small_best_cp <- RT_small_fit_tune$bestTune
ggplot(RT_small_fit_tune)

RT_small_fit <- RT_train_small %>% rpart(value_eur ~ age + league + strongest_position + squad_rank + 
                                           european_competition + international_reputation + yrs_left_on_contract, 
                                         data =., control = rpart.control(cp = RT_small_best_cp))
RT_predict_small <- RT_test_small %>% predict(RT_small_fit, newdata = .)
RMSE(RT_test_small$value_eur, RT_predict_small)


RT_test_small %>% mutate(predictions = predict(RT_small_fit, newdata = .)) %>%
 # mutate(adjusted_predict = case_when(predictions <= 0 ~ 0, predictions > 0 ~ predictions)) %>%
  ggplot(aes(value_eur, predictions)) +
  labs(x = "True Value", y = "Predicted Value") +
  geom_point()+ geom_abline()

## Let's use the full training set

RT_tune <- train(value_eur ~ age + league + strongest_position + squad_rank + 
                             european_competition + international_reputation + yrs_left_on_contract,
                           method = "rpart", tuneGrid = data.frame(cp = seq(0, 0.01, len = 100)), data = train)
RT_best_cp <- RT_tune$bestTune # Having run a sequence of possible tuning parameters through we save the optimal choice.
ggplot(RT_tune) + labs( y = "Resulting RMSE") ## We see the plot of the possible tuning parameters, with our optimal choice at the graphs minimum point.

RT_fit <- train %>% rpart(value_eur ~ age + league + strongest_position + squad_rank + 
                                           european_competition + international_reputation + yrs_left_on_contract, 
                                         data =., control = rpart.control(cp = RT_best_cp))
RT_predict <- test %>% predict(RT_fit, newdata = .)
RT_result <- RMSE(test$value_eur, RT_predict)
rmse_results <- bind_rows(rmse_results,
                         data_frame(method="Regression Tree",
                                   RMSE = RT_result))
## We can see that this model has performed admirably in comparison to previous models. This model shall be used as our 
## final attempt.
test %>% mutate(predictions = predict(RT_fit, newdata = .)) %>%
  ggplot(aes(value_eur, predictions)) +
  labs(x = "True Value", y = "Predicted Value") +
  geom_point()+ geom_abline()

RT_tune$finalModel ## We can looked closer at the splits made in the model using this line of code.
## There are too many nodes to show all but early splits are dependent on international reputation and age mostly.



#################################################################################################################################
############################################# TEST AGAINST THE VALIDATION SET ###################################################
## FM stands for final model
## We use the same method as above but we now build on the full training set and test on the validation set we put aside earlier.
FM_tune <- train(value_eur ~ age + league + strongest_position + squad_rank + 
                   european_competition + international_reputation + yrs_left_on_contract,
                 method = "rpart", tuneGrid = data.frame(cp = seq(0, 0.01, len = 100)), data = training_data)
FM_best_cp <- FM_tune$bestTune # Save our optimal choice of tuning parameter cp.
ggplot(FM_tune) 
## We fit our model using our chosen cp and relevant features using rpart.
FM_fit <- training_data %>% rpart(value_eur ~ age + league + strongest_position + squad_rank + 
                            european_competition + international_reputation + yrs_left_on_contract, 
                          data =., control = rpart.control(cp = FM_best_cp))
FM_predict <- validation_set %>% predict(FM_fit, newdata = .) # We make our predictions.
FM_result <- RMSE(validation_set$value_eur, FM_predict) # Save the resulting RMSE
FM_result

## Our final result is 3,209,748. This means we will usually be about 3.2 million Euros out on our predictions of a players
## value. 

## Add our final model to our results table
rmse_results <- bind_rows(rmse_results,
                          data_frame(method="Final Model",
                                     RMSE = FM_result))
## Let's have a quick inspection of the errors returned.
errors <- validation_set$value_eur - FM_predict
hist(errors)
hist(errors, xlim = c(-10000000, 10000000), breaks = 100, xlab = "Error (Player Value in Euros)") 
# As we would expect, the errors appear to follow a normal dist.
# with mean 0, hence why we used RMSE to gain the insight we needed.
summary(errors)   ## mean of errors is - 18,807. This is very small in magnitude and a very good outcome.
sd(errors)        ## sd of errors and RMSE are very close. To be expected???

final_plot <- data.frame(validation_set$value_eur, FM_predict)
final_plot %>% ggplot(aes(validation_set$value_eur, FM_predict)) +
  labs(x = "True Value", y = "Predicted Value") +
  geom_point()+ geom_abline()

save.image(file='fifaplayers_env.RData')
#load('fifaplayers_env.RData')

